spring:
  datasource:
    url: jdbc:postgresql://10.140.0.3:5432/postgresql
#    url: jdbc:postgresql://localhost:5432/postgresql
    username: postgresql
    password: postgrespassword
    hikari:
      connectionTimeout: 30000
      maximumPoolSize: 15
      maxLifetime: 1800000
      poolName: HikariCP
      readOnly: false
      connectionTestQuery: SELECT 1
  jpa:
    show-sql: false
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
  rabbitmq:
    host: 10.178.0.8
    username: guest
    password: guest
    port: 5672